sudo: false
cache: bundler
language: ruby

rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4

script: bundle exec rspec && bundle exec rubocop

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 5"
